# Generated by Django 5.0.6 on 2024-06-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('Fname', models.CharField(max_length=250)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
