# Generated by Django 5.0.6 on 2024-06-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=250)),
                ('course_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=250)),
                ('link_url', models.CharField(max_length=250)),
            ],
        ),
    ]
