# Generated by Django 5.0.6 on 2024-06-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_name', models.CharField(max_length=250)),
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_level', models.CharField(max_length=250)),
                ('image_url', models.CharField(max_length=250)),
                ('link_url', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
