# Generated by Django 5.0.6 on 2024-06-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_courses_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileName', models.CharField(max_length=250)),
                ('avatar_url', models.CharField(max_length=250)),
            ],
        ),
    ]
