# Generated by Django 5.0.6 on 2024-06-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0004_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('Student_Name', models.CharField(max_length=250)),
                ('Student_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Student_Age', models.CharField(max_length=250)),
                ('Student_Level', models.CharField(max_length=250)),
                ('Student_Gender', models.CharField(max_length=250)),
                ('Student_Image', models.CharField(max_length=250)),
            ],
        ),
    ]
