# Generated by Django 5.0.6 on 2024-06-07 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0005_studentinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentInformation',
            fields=[
                ('Parent_Name', models.CharField(max_length=250)),
                ('Parent_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Parent_Image', models.CharField(max_length=250)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.studentinformation')),
            ],
        ),
    ]
