# Generated by Django 5.0.6 on 2024-06-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0006_parentinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInformation',
            fields=[
                ('Teacher_Name', models.CharField(max_length=250)),
                ('Teacher_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Teacher_Age', models.CharField(max_length=250)),
                ('Teacher_Gender', models.CharField(max_length=250)),
                ('Course_Handle', models.CharField(max_length=250)),
                ('Teacher_Image', models.CharField(max_length=250)),
            ],
        ),
    ]
