# Generated by Django 5.0.6 on 2024-06-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0008_studentteachermessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentteachermessages',
            name='Received_Message_Student',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='studentteachermessages',
            name='Received_Message_Teacher',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='studentteachermessages',
            name='Sent_Message_Student',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='studentteachermessages',
            name='Sent_Message_Teacher',
            field=models.CharField(max_length=4000),
        ),
    ]
