# Generated by Django 5.0.6 on 2024-06-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0018_studentteachermessages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('Name', models.CharField(max_length=250)),
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Teacher_Age', models.CharField(max_length=250)),
                ('Gender', models.CharField(max_length=250)),
                ('Course', models.CharField(max_length=250)),
                ('Image', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentTeacherMessages',
        ),
    ]
