# Generated by Django 5.0.6 on 2024-06-08 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0020_studentteachermessage_delete_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTeacherCommunication',
            fields=[
                ('Sent_Message_Student', models.CharField(max_length=4000)),
                ('Received_Message_Student', models.CharField(max_length=4000)),
                ('Sent_Message_Teacher', models.CharField(max_length=4000)),
                ('Received_Message_Teacher', models.CharField(max_length=4000)),
                ('Message_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Message_Date', models.CharField(max_length=250)),
                ('Message_Hour', models.IntegerField()),
                ('Message_Minute', models.IntegerField()),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.studentinformation')),
                ('Teacher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.teacherinformation')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentTeacherMessage',
        ),
    ]
