# Generated by Django 5.0.6 on 2024-06-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0021_studentteachercommunication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_previous_Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.IntegerField(unique=True)),
                ('Teacher_ID', models.IntegerField(unique=True)),
                ('Student_url', models.CharField(max_length=250)),
                ('Teacher_url', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
