# Generated by Django 5.0.6 on 2024-06-08 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0023_alter_new_previous_profiles_student_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTeacherCommunications',
            fields=[
                ('Message_text', models.CharField(max_length=4000)),
                ('Message_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Message_Date', models.CharField(max_length=250)),
                ('Message_Hour', models.IntegerField()),
                ('Message_Minute', models.IntegerField()),
                ('Message_Source', models.IntegerField()),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.studentinformation')),
                ('Teacher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.teacherinformation')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentTeacherCommunication',
        ),
    ]
