# Generated by Django 5.0.6 on 2024-06-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0024_studentteachercommunications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialInformation',
            fields=[
                ('MaterialID', models.AutoField(primary_key=True, serialize=False)),
                ('PublisherImage', models.CharField(max_length=250)),
                ('PublisherName', models.CharField(max_length=250)),
                ('DateOfPublish', models.CharField(max_length=250)),
                ('DescriptionText', models.CharField(max_length=4000)),
                ('MaterialPath', models.CharField(max_length=250)),
                ('MaterialIcon', models.CharField(max_length=250)),
            ],
        ),
    ]
