# Generated by Django 5.0.6 on 2024-06-09 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0025_materialinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContents',
            fields=[
                ('MaterialID', models.AutoField(primary_key=True, serialize=False)),
                ('PublisherImage', models.CharField(max_length=250)),
                ('PublisherName', models.CharField(max_length=250)),
                ('DateOfPublish', models.CharField(max_length=250)),
                ('DescriptionText', models.CharField(max_length=4000)),
                ('MaterialPath', models.CharField(max_length=250)),
                ('MaterialIcon', models.CharField(max_length=250)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.courses')),
            ],
        ),
        migrations.DeleteModel(
            name='MaterialInformation',
        ),
    ]
