# Generated by Django 5.0.6 on 2024-07-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0027_parentinformationsd_delete_parentinformation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParentInformationsd',
            new_name='ParentInformation',
        ),
    ]
