# Generated by Django 5.0.6 on 2024-07-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0028_rename_parentinformationsd_parentinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinformation',
            name='Passwordd',
            field=models.CharField(default=1234, max_length=250),
            preserve_default=False,
        ),
    ]
