# Generated by Django 5.0.6 on 2024-07-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0029_teacherinformation_passwordd'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformation',
            name='Passwordd',
            field=models.CharField(default=1234, max_length=250),
            preserve_default=False,
        ),
    ]
